faiss_db:
  collection_name: "owners_manual_collection"

embedding_model:
  provider: "fastembed"
  model_name: "BAAI/bge-small-en-v1.5"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0.3
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
